import { useEffect, useState } from "react";
import Head from 'next/head'

export default function Home() {

    const [restaurants, setRestaurants] = useState([]);

    useEffect(() => {
        // handler()
        (async () => {
            const results =  await fetch("/api/list").then(response => response);
            setRestaurants(results);
        })();
    }, []);

    const getData  =async()=>{
        const results =  await fetch("/api/versalData").then(response => response);
        console.log(results,'ayush@123')
    }

    return (
        <div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                <h1 >
                    MongoDB with <a href="https://nextjs.org">Next.js!</a> Example
                </h1>
                <br />
                <div >
                    {Object.keys(restaurants).length>0 && <div  key={restaurant._id}>
                            <h2>{restaurant.fruit}</h2>
                            <p>{restaurant.size}</p>
                            <p>{restaurant.color}</p>
                        </div>}
                
                </div>
                <button onClick={()=>getData()}>
                    call versla api
                </button>
            </main>
        </div>
    )
}